name: ordermanagement
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  drag_and_drop_lists: ^0.3.2+2
  get: ^4.6.5
  cached_network_image: ^3.2.1
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0
  liquid_swipe: ^3.0.0
  lottie: ^1.4.2
  url_strategy: ^0.2.0
  qr_flutter: ^4.0.0
  dio: ^4.0.6
  logger: ^1.1.0
  get_storage: ^2.0.3
  http: ^0.13.5
  jiffy: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
