Map<String, String> enLang = {
  'splash_header' : 'qwe',
  'splash_subtitle' : 'Whether you need a desk, office, suite, or entire HQ, we create environments that increase productivity, innovation and collaboration.',
  'sign_in_workspace' : 'Sign in to workspace',
  'log_in' : 'Log In',
  'login' : 'Login',
  'email' : 'Email',
  'username' : 'Username',
  'enter_your_obj' : 'Enter your @obj',
  'password' : 'Password',
  'newPassword' : 'New password',
  'created_on_date' : 'Created on @date',
  'menu' : 'Menu',
  'add_obj' : 'Add @obj',
  'column' : 'Column',
  'card' : 'Card',
  'home_header' : 'Some big big header text',
  'home_subtitle' : 'Some big small little something text some big small little something text',
  'terms_conditions' : 'Terms & Conditions',
  'allow_notification_subtitle' : 'Allow notification services to this and that',
  'enter_obj' : 'Enter @obj',
  'allow_obj' : 'Allow @obj',
  'order_number' : 'Order number',
  'notification' : 'Notification',
  'validUserName' : 'Username can not be empty',
  'validPhoneNumber' : 'Phone number must at-least 9 characters',
  'validEmail' : 'Please enter a correct email address',
  'validObj' : '@obj can not be empty',
  'validPassword' : 'Password must be at-least 6 character',
  'staff' : 'Staff',
  'name' : 'Name',
  'update_obj' : 'Update @obj',
  'update' : 'Update',
  'phone_number' : 'Phone number',
  'cancel' : 'Cancel',
  'add' : 'Add',
  'profile' : 'Profile',
  '' : '',
};