Map<String, String> enLang = {
  'splash_header' : 'Beautiful Workspace in the heart\nof your city',
  'splash_subtitle' : 'Whether you need a desk, office, suite, or entire HQ, we create environments that increase productivity, innovation and collaboration.',
  'sign_in_workspace' : 'Sign in to workspace',
  'log_in' : 'Log In',
  'login' : 'Login',
  'email' : 'Email',
  'username' : 'Username',
  'enter_your_obj' : 'Enter your @obj',
  'password' : 'Password',
  'created_on_date' : 'Created on @date',
  'menu' : 'Menu',
  'add_obj' : 'Add @obj',
  'column' : 'Column',
  'card' : 'Card',
  'home_header' : 'Some big big header text',
  'home_subtitle' : 'Some big small little something text some big small little something text',
  'terms_conditions' : 'Terms & Conditions',
  'allow_notification_subtitle' : 'Allow notification services to this and that',
  'enter_obj' : 'Enter @obj',
  'allow_obj' : 'Allow @obj',
  'order_number' : 'Order number',
  'notification' : 'Notification',
  'validUserName' : 'Username can not be empty',
  'validPassword' : 'Password must be at-least 6 character',
  '' : '',
};